### PR TITLE
fix border appears when selecting range

### LINKED ISSUE #11: Grid border appears on the terminal
When scaling the UI by pressing `ctrl` + `plus`/`minus`, the grid border appears on the terminal.

image

And... How to disable egui default keybinding?

### PR DESCRIPTION
**Pull request by iamazy**
fix #11

### CODE REVIEW

File: src/view.rs [hunk 1]
```diff
@@ -272,16 +282,17 @@ impl<'a> TerminalView<'a> {
 
             if is_inverse || is_selected {
                 std::mem::swap(&mut fg, &mut bg);
-            }
 
-            painter.rect_filled(
```
Comment (Harzu) [inline src/view.rs:277]: This rect rendered the cell background for example if you run `htop` you can't see any background colors for cells without this rect.

below is expected behaviour
Screenshot 2025-01-15 at 21 55 53

below is actual (with this fix)
Screenshot 2025-01-15 at 21 54 25

Comment (iamazy) [reply src/view.rs:277]: I tried to fix this problem, but I can't found ratio in default theme

image
